config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  resources :posts

end

app/models/image.rb
class Image < ActiveRecord::Base
    mount_uploader :avatar, AvatarUploader
end

app/models/post.rb
class Post < ActiveRecord::Base
    mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
    require 'carrierwave/orm/activerecord'
    def index
        @image = Image.new
        #uploader = AvatarUploader.new
        #@test = uploader.retrieve_from_store!('default.jpg')
    end
    
    def create
        # uploader = AvatarUploader.new
        @image = Image.new(image_params)
        # uploader.store!(@image.avatar)

        if @image.save
            redirect_to image_path(@image)
        end
    end
    
    def show
        @image = Image.find(params[:id])
        # uploader = AvatarUploader.new
        # @my_file = uploader.retrieve_from_store!(@image.avatar)
    end
    
    def image_params
        params.require(:image).permit(:name,:avatar)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    require 'carrierwave/orm/activerecord'
    def index
        @posts = Post.all
    end
    
    def new
        @post = Post.new
    end
    
    def create
        @post = Post.new(post_params)
        if @post.save
            redirect_to posts_path(@post)
        end
    end
    
    def show
        @post = Post.find(params[:id])
    end
    
    def post_params
        params.require(:post).permit(:picture,:picture_cache)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/images/index.html.erb
<h1>Hi and welcome to this Index Page!</h1>

<p>
    I'll be uploading some cool images here :D
    
    -> From a file already in Rails's public folder
    <br/>
    <img src="/default.jpg"/>
    <hr/>
    
    -> From a file already on the web somewhere (fancy Google?)
    
    <hr/>
    
    -> Choose your file to upload!!
    <%= form_for @image do |f| %>
        Name: <%= f.text_field :name %> <br/>
        Image: <%= f.file_field :avatar %><br/>
        <%= f.submit %>
    <% end %>
    
</p>

app/views/images/show.html.erb
<h1>Hii you saved an image: <%= @image.name %> </h1>

<%= image_tag(@image.avatar) %>

app/views/layouts/_footer.html.erb
<script>
  $(document).ready(function() {

   var docHeight = $(window).height();
   var footerHeight = $('#footer').height();
   var footerTop = $('#footer').position().top + footerHeight;

   if (footerTop < docHeight) {
    $('#footer').css('margin-top', -10+ (docHeight - footerTop) + 'px');
   }
  });
 </script>

<% (2015 == Time.now.year) ? @year = "2015" : @year = "2015 - #{Time.now.year}" %>
<div id="footer">
	<div class="container">
		<div class="col-md-12">
			<center><h6>© <%= @year %> Breena M. Theseira, unless otherwise stated.</h6></center>
		</div>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">Upload Pictures!</div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %><span class="sr-only">(current)</span></a></li>        
        <li class="active"><%= link_to "Upload My Picture!", new_post_path %><span class="sr-only">(current)</span></a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<%= render 'layouts/navbar' %>
<body>
	<div class="container-fluid">
		<%= yield %>
	</div>
	<br/>
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/posts/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-9">
			<h2>All Pictures</h2>
		</div>
		<div class="col-md-3">
			<%= link_to "Upload Picture", new_post_path, class: "btn btn-default btn-group-justified", style: "margin-top:20px;" %>
		</div>
	</div>
	<br/>
	<div class="well">
		<div class="row">
			<% @posts.each do |p| %>
				<div class="col-md-3">
					<%= link_to "#{image_tag(p.picture_url, height: '200',class: 'thumbnail')}".html_safe, post_path(p.id)  %>
				</div>
			<% end %>
		</div>
	</div>	
	<br/>
</div>

app/views/posts/new.html.erb
<div class="container">	
	<div class="row">
		<div class="col-md-12">
			<h2>New Picture</h2>
		</div>
	</div>
	<br/>
	<div class="row">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Click the 'Choose File' to upload your picture!</h3>
			</div> 
			<div class="panel-body">
				<%= form_for @post do |f| %>
				    <%= f.file_field :picture, class: "btn btn-default", accept: "image/png,image/gif,image/jpeg" %>
				    <br/>
				    <%= f.hidden_field :picture_cache %>
				    <br/>
				    <%= f.submit "Add Picture", class: "btn btn-default btn-group-justified" %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<div class="container">	
	<div class="row">
		<div class="col-md-12">
			<h2>Show Picture ID: <%= @post.id %></h2>
		</div>
	</div>
	<br/>
	<div class="row">
		<div class="col-md-4">
			<center><%= image_tag(@post.picture_url, size: '250px') %></center>
		</div>
		<div class="col-md-8">		
			Date uploaded:<br/>
			<%= @post.created_at %><br/>
			<br/>
			URL:<br/>
			<%= @post.picture_url %>
		</div>
	</div>	
	<br/>
	<%= link_to "All Pictures", posts_path, class: "btn btn-default btn-group-justified" %>
</div>